services:
  - type: web
    name: inventario-edulend
    env: docker
    region: ohio
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
